version: '3'
services:
  spectrum_lite_model:
    # Here you can specify an env-file with variables
    # that can be used in the docker-container,
    # BUT these variables can not be used here in the
    # docker-compose using ${...} UNLESS it is a file named
    # ".env". This file (in the same directory) is always
    # loaded into the docker-compose, but not into the 
    # docker-containers unless the variables are mapped in the 
    # environment option below or using the env_file option here.
    env_file: .env
    container_name: spectrum_lite_model
    build:
      context: .
      dockerfile: Dockerfile
    environment: # specify the env-variables here
      # variables from .env file or system
      API_KEY_ML: ${API_KEY_ML}
      API_SECRET_ML: ${API_SECRET_ML}
      API_ENDPOINT_ML: ${API_ENDPOINT_ML}
      SCHEDULE_HOUR: ${SCHEDULE_HOUR}
      SCHEDULE_MINUTE: ${SCHEDULE_MINUTE}
      DEAL_STAGE_VALUE: ${DEAL_STAGE_VALUE}
      DEAL_CLOSING_DATE_OPERATOR: ${DEAL_CLOSING_DATE_OPERATOR}
      DEAL_CLOSING_DATE_VALUE: ${DEAL_CLOSING_DATE_VALUE}
      # sometimes the console won't show print messages,
      # using PYTHONUNBUFFERED: 1 can fix this
      PYTHONUNBUFFERED: 1
